/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ApAnt {
      'mediaStatus': any;
    }
  }

  interface HTMLApAntElement extends StencilComponents.ApAnt, HTMLStencilElement {}

  var HTMLApAntElement: {
    prototype: HTMLApAntElement;
    new (): HTMLApAntElement;
  };
  interface HTMLElementTagNameMap {
    'ap-ant': HTMLApAntElement;
  }
  interface ElementTagNameMap {
    'ap-ant': HTMLApAntElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ap-ant': JSXElements.ApAntAttributes;
    }
  }
  namespace JSXElements {
    export interface ApAntAttributes extends HTMLAttributes {
      'mediaStatus'?: any;
      'onOnTogglePLay'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface ApTogglePlay {
      'paused': boolean;
    }
  }

  interface HTMLApTogglePlayElement extends StencilComponents.ApTogglePlay, HTMLStencilElement {}

  var HTMLApTogglePlayElement: {
    prototype: HTMLApTogglePlayElement;
    new (): HTMLApTogglePlayElement;
  };
  interface HTMLElementTagNameMap {
    'ap-toggle-play': HTMLApTogglePlayElement;
  }
  interface ElementTagNameMap {
    'ap-toggle-play': HTMLApTogglePlayElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ap-toggle-play': JSXElements.ApTogglePlayAttributes;
    }
  }
  namespace JSXElements {
    export interface ApTogglePlayAttributes extends HTMLAttributes {
      'onOnTogglePLay'?: (event: CustomEvent) => void;
      'paused'?: boolean;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
